namespace Heroes_Descent.Core.Entities.Heroes;

// The Warrior is a durable frontline fighter.
// Secondary stat : Strength — increases physical attack damage.
// Resource       : Rage (0–100) — generated by attacking and taking hits.
//                  Undying Rage costs 40 Rage to activate.
public class Warrior : Hero
{
    // --- Secondary stat ---

    // Strength is added on top of BaseAttack every time the Warrior attacks.
    // Increases by 3 on each level-up.
    public int Strength { get; private set; } = 10;

    // --- Rage resource ---

    public int MaxRage { get; } = 100;
    public int CurrentRage { get; private set; } = 0;

    private const int AbilityCost  = 40;   // Rage required to activate Undying Rage
    private const int RageOnAttack = 10;   // Rage gained per basic attack
    private const int RageOnHitMin = 5;    // Minimum Rage gained when taking damage

    // True while Undying Rage is active (within 5 s of activation).
    // The game engine checks this before applying damage and skips the hit entirely.
    private DateTime? _undyingRageExpiry;
    public bool IsUntargetable => _undyingRageExpiry.HasValue && DateTime.UtcNow < _undyingRageExpiry.Value;

    // 30-second cooldown after each use.
    private DateTime? _undyingRageCooldownExpiry;
    private bool IsOnCooldown => _undyingRageCooldownExpiry.HasValue && DateTime.UtcNow < _undyingRageCooldownExpiry.Value;

    public Warrior(string name)
    {
        Name = name;
        Class = HeroClass.Warrior;
        MaxHp     = 120;
        BaseAttack = 15;
        Defense   = 10;
        Speed     = 7;        // Warrior acts last — trades speed for durability
        CurrentHp = MaxHp;
    }

    public override string AbilityName => "Undying Rage";
    public override string AbilityDescription =>
        $"Costs {AbilityCost} Rage. Become untargetable for 5 seconds. 30 s cooldown.";

    // Attacks for BaseAttack + Strength and generates Rage.
    // Strength bonus rewards investing in this stat through leveling.
    public override int BasicAttack()
    {
        GainRage(RageOnAttack);
        return BaseAttack + Strength;
    }

    // Called automatically by Hero.TakeDamage() after every hit.
    // The more damage the Warrior soaks, the more Rage they build —
    // encouraging them to stay in the fight and block at the right moment.
    protected override void OnDamageTaken(int damageTaken)
    {
        // Minimum RageOnHitMin, then scales with damage taken
        int rageGained = RageOnHitMin + (damageTaken / 5);
        GainRage(rageGained);
    }

    // Adds Rage without exceeding the maximum.
    public void GainRage(int amount) =>
        CurrentRage = Math.Min(MaxRage, CurrentRage + amount);

    // The game engine calls this to check whether to show the ability as available.
    public override bool CanUseAbility() => CurrentRage >= AbilityCost && !IsOnCooldown;

    // Spends 40 Rage and activates Undying Rage for 5 seconds.
    // Returns 0 — there is no outgoing damage; the effect is purely defensive.
    // Game engine: check warrior.IsUntargetable before applying any hit and skip it.
    public override int UseAbility()
    {
        if (CurrentRage < AbilityCost) return 0;
        CurrentRage -= AbilityCost;
        _undyingRageExpiry        = DateTime.UtcNow.AddSeconds(5);
        _undyingRageCooldownExpiry = DateTime.UtcNow.AddSeconds(30);
        return 0;
    }

    public override void FullRestore()
    {
        base.FullRestore();
        CurrentRage = 0;
        _undyingRageExpiry         = null;
        _undyingRageCooldownExpiry = null;
    }

    // On level-up, Warrior gains HP, Strength, and Defense.
    protected override void OnLevelUp()
    {
        MaxHp     += 15;
        CurrentHp  = Math.Min(CurrentHp + 15, MaxHp);
        Strength  += 3;
        Defense   += 2;
    }
}
